
/*<!-- saved from url=(0092)https://4shared-api.googlecode.com/hg/src/com/pmstation/shared/soap/client/ApiException.java -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">
 * */
 
package neembuu.uploader.uploaders.api._4shared;

import neembuu.uploader.uploaders.api._4shared.FaultBean;
import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ApiException", targetNamespace = "http://api.soap.shared.pmstation.com/")
public class ApiException
        extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultBean faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ApiException(String message, FaultBean faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ApiException(String message, FaultBean faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.pmstation.shared.soap.client.FaultBean
     */
    public FaultBean getFaultInfo() {
        return faultInfo;
    }
}
/*</pre></body><link rel="stylesheet" type="text/css" href="data:text/css,"><style type="text/css">embed[type*="application/x-shockwave-flash"],embed[src*=".swf"],object[type*="application/x-shockwave-flash"],object[codetype*="application/x-shockwave-flash"],object[src*=".swf"],object[codebase*="swflash.cab"],object[classid*="D27CDB6E-AE6D-11cf-96B8-444553540000"],object[classid*="d27cdb6e-ae6d-11cf-96b8-444553540000"],object[classid*="D27CDB6E-AE6D-11cf-96B8-444553540000"]{	display: none !important;}</style></html>*/