/*
<!-- saved from url=(0094)https://4shared-api.googlecode.com/hg/src/com/pmstation/shared/soap/client/DesktopAppJax2.java -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">
 */
package neembuu.uploader.uploaders.api._4shared;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DesktopAppJax2", targetNamespace = "http://api.soap.shared.pmstation.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DesktopAppJax2 {

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String login(
            @WebParam(name = "arg0", partName = "arg0") String arg0,
            @WebParam(name = "arg1", partName = "arg1") String arg1);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean hasRightUpload();

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns long
     * @throws ApiException
     */
    @WebMethod
    @WebResult(partName = "return")
    public long uploadStartFile(
            @WebParam(name = "arg0", partName = "arg0") String arg0,
            @WebParam(name = "arg1", partName = "arg1") String arg1,
            @WebParam(name = "arg2", partName = "arg2") long arg2,
            @WebParam(name = "arg3", partName = "arg3") String arg3,
            @WebParam(name = "arg4", partName = "arg4") long arg4)
            throws ApiException;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws ApiException
     */
    @WebMethod
    @WebResult(partName = "return")
    public String createUploadSessionKey(
            @WebParam(name = "arg0", partName = "arg0") String arg0,
            @WebParam(name = "arg1", partName = "arg1") String arg1,
            @WebParam(name = "arg2", partName = "arg2") long arg2)
            throws ApiException;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns long
     * @throws ApiException
     */
    @WebMethod
    @WebResult(partName = "return")
    public long getNewFileDataCenter(
            @WebParam(name = "arg0", partName = "arg0") String arg0,
            @WebParam(name = "arg1", partName = "arg1") String arg1)
            throws ApiException;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getUploadFormUrl(
            @WebParam(name = "arg0", partName = "arg0") int arg0,
            @WebParam(name = "arg1", partName = "arg1") String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws ApiException
     */
    @WebMethod
    @WebResult(partName = "return")
    public String uploadFinishFile(
            @WebParam(name = "arg0", partName = "arg0") String arg0,
            @WebParam(name = "arg1", partName = "arg1") String arg1,
            @WebParam(name = "arg2", partName = "arg2") long arg2,
            @WebParam(name = "arg3", partName = "arg3") String arg3)
            throws ApiException;

    @WebMethod
    @WebResult(partName = "return")
    public String getFileDownloadLink(
            @WebParam(name = "arg0", partName = "arg0") String arg0,
            @WebParam(name = "arg1", partName = "arg1") String arg1,
            @WebParam(name = "arg2", partName = "arg2") long arg2)
            throws ApiException;
}

/*
</pre></body><link rel="stylesheet" type="text/css" href="data:text/css,"><style type="text/css">embed[type*="application/x-shockwave-flash"],embed[src*=".swf"],object[type*="application/x-shockwave-flash"],object[codetype*="application/x-shockwave-flash"],object[src*=".swf"],object[codebase*="swflash.cab"],object[classid*="D27CDB6E-AE6D-11cf-96B8-444553540000"],object[classid*="d27cdb6e-ae6d-11cf-96b8-444553540000"],object[classid*="D27CDB6E-AE6D-11cf-96B8-444553540000"]{	display: none !important;}</style></html>*/